name: docs
on:
  push: { branches: [ main ] }
  workflow_dispatch:

permissions:
  contents: write   # <-- needed to push to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0           # safer for the publisher action
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -e . mkdocs-material mkdocstrings[python] pymdown-extensions
      - run: mkdocs build --strict -f docs/mkdocs.yml   # uses /docs/mkdocs.yml
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: gh-pages
          force_orphan: true       # creates a clean orphan branch on first deploy